package:
  name: libastra
  version: '1.9.0.dev11'

source:
  git_url: https://github.com/ahendriksen/astra-toolbox.git
  git_tag: use-conda-compiler-toolchain

build:
  number: 0
  script_env:
    - CC # [linux]
    - CXX # [linux]

requirements:
  build:
    - {{ compiler('c') }} # [win or linux]
    - {{ compiler('cxx') }} # [linux]
    - boost-cpp # [osx or linux]
    - automake # [osx]
    - autoconf # [osx]
    - libtool # [osx]
    - cudatoolkit {{ cudatoolkit }} # [linux]
  host:
    - boost-cpp # [osx or linux]
  run:
    # See: https://github.com/conda-forge/conda-forge.github.io/issues/687#issuecomment-460095230
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }} # [linux]

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'
